### ISSUE TITLE
`uni retrieve`

### ISSUE THREAD

**Issue by rabuu** [rabuu/uni-cli#2]
Opposite feature to `uni export`: Copy/move files into a workdir

```toml
[[Courses.foo.RetrieveFile]]
  From = "~/Downloads/Blatt{{.Number}}.pdf"
  To = "blatt{{.Number}}.pdf"
```
